services:
    db:
        container_name: db
        image: ghcr.io/identicum/postgres:16
        pull_policy: always
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: postgrespwd
        volumes:
            - ./db/init/:/docker-entrypoint-initdb.d/:ro

    idp:
        container_name: idp
        image: ghcr.io/identicum/keycloak:26.1
        pull_policy: always
        restart: always
        ports:
            - 8080:8080
        env_file:
            - ./keycloak.env
        depends_on:
            db:
                condition: service_healthy

    idp_config:
        container_name: idp_config
        image: ghcr.io/identicum/sherpa-deploy:latest
        pull_policy: always
        volumes:
            - ./terraform/:/usr/home/
        command: "./apply.sh"
        depends_on:
            idp:
                condition: service_healthy

    launcher:
        container_name: launcher
        image: ghcr.io/identicum/launcher:latest
        pull_policy: always
        restart: always
        ports:
            - 8081:8081
        environment:
            - APP_PARAMETERS=--spring.config.location=/config/application.properties --logging.level.org.springframework.security=DEBUG
        volumes:
            - ./application.properties:/config/application.properties:ro
            # - ./data.json:/data/data.json:ro
            # - ../target/launcher.jar:/app/launcher.jar
        depends_on:
            idp_config:
                condition: service_completed_successfully

    ipax:
        container_name: ipax
        image: ghcr.io/identicum/ipax:latest
        pull_policy: always
        restart: always
        ports:
            - 80:80
        environment:
            NGINX_RESOLVER: 127.0.0.11 valid=5s
            NGINX_LOG_LEVEL: debug
            OIDC_DISCOVERY: http://idp:8080/realms/launcher/.well-known/openid-configuration
            OIDC_CLIENT_ID: ipax_client_id
            OIDC_CLIENT_SECRET: ipax_client_secret
            OIDC_SCOPE: openid profile email launcher_scope
            OIDC_POST_LOGOUT_REDIRECT_URI: http://localhost/logoutSuccess.html
